name: MLflow CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  train-and-docker:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # ===== SETUP CONDA =====
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-activate-base: true

    # ===== INSTALL MLFLOW CLI (RUNNER LEVEL) =====
    - name: Install MLflow CLI
      run: |
        pip install mlflow

    - name: Verify MLflow
      run: |
        mlflow --version
        which mlflow

    # ===== RUN MLFLOW PROJECT =====
    - name: Run MLflow Project
      run: |
        mlflow run ./MLProject \
          -P data_dir=data \
          -P n_estimators=200 \
          -P max_depth=20

        RUN_ID=$(ls mlruns/*/*/ | head -n 1 | awk -F/ '{print $3}')
        echo $RUN_ID > run_id.txt

    # ===== SAVE ARTIFACTS =====
    - name: Upload MLflow artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-artifacts
        path: mlruns/

    # ===== DOCKER HUB LOGIN =====
    - name: Login Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    # ===== BUILD DOCKER IMAGE =====
    - name: Build Docker image with MLflow
      run: |
        RUN_ID=$(cat run_id.txt)
        mlflow models build-docker \
          --model-uri runs:/$RUN_ID/model \
          --name ${{ secrets.DOCKER_HUB_USERNAME }}/rf-mlflow

    # ===== PUSH IMAGE =====
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/rf-mlflow
